routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\ItemsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login', function () {
    return view('dashboard.login');
})->name('dashboard.sign-in');


Route::post('login', [AuthController::class, 'login'])->name('login');


Route::group([
    'middleware' => 'admin.auth'
], function () {
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/', function () {
        return view('dashboard.index');
    });


    Route::group([
        'prefix' => 'categories'
    ], function () {
        Route::get('/', [CategoryController::class, 'index'])->name('categories.index');
        Route::get('/create', [CategoryController::class, 'create'])->name('categories.create');
        Route::post('/store', [CategoryController::class, 'store'])->name('categories.store');
        Route::get('/destroy/{category}', [CategoryController::class, 'destroy'])->name('categories.destroy');
        Route::get('/edit/{category}', [CategoryController::class, 'edit'])->name('categories.edit');
        Route::post('/update/{category}', [CategoryController::class, 'update'])->name('categories.update');
    });


    Route::group([
        'prefix' => 'items'
    ], function () {
        Route::get('/', [ItemsController::class, 'index'])->name('items.index');
        Route::get('/create', [ItemsController::class, 'create'])->name('items.create');
        Route::post('/store', [ItemsController::class, 'store'])->name('items.store');
        Route::get('/destroy/{category}', [ItemsController::class, 'destroy'])->name('items.destroy');
        Route::get('/edit/{category}', [ItemsController::class, 'edit'])->name('items.edit');
        Route::post('/update/{category}', [ItemsController::class, 'update'])->name('items.update');
    });

    Route::group([
        'prefix' => 'discount'
    ], function () {
        Route::get('/', [DiscountController::class, 'index'])->name('discount.index');
        Route::get('/create', [DiscountController::class, 'create'])->name('discount.create');
        Route::post('/store', [DiscountController::class, 'store'])->name('discount.store');
        Route::get('/destroy/{category}', [DiscountController::class, 'destroy'])->name('discount.destroy');
    });
});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class)->with('parent');
    }
    public function discount()
    {
        return $this->belongsTo(Discount::class);
    }
    public function getDiscountPriceAttribute()
    {
        $discount_value = 0;

        // all menu discount
        if (Discount::where('type', 'all')->count() > 0)
            $discount_value += Discount::where('type', 'all')->first()->amount;

        // item discount
        if ($this->discount_id)
            $discount_value = $this->discount->amount;

        // category discount
        if ($this->category->discount_id) {
            $discount_value += $this->category->discount->amount;
            if ($this->category->depth >= 2)
                $discount_value += $this->category->parent->discount->amount;
            if ($this->category->depth >= 3)
                $discount_value += $this->category->parent->parent->discount->amount;
            if ($this->category->depth >= 4)
                $discount_value += $this->category->parent->parent->parent->discount->amount;
        }

        return ($this->price * $discount_value) / 100;
    }
}

app/Http/Controllers/ItemsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class ItemsController extends Controller
{
    public function index()
    {
        $items = Item::with('category')->get();
        return view(
            'dashboard.item.index',
            [
                'datas' => $items,
            ]
        );
    }

    public function create()
    {
        return view(
            'dashboard.item.create',
            [
                'categories' => Category::get(),
            ]
        );
    }
    public function store(Request $request)
    {

        $item = new Item();
        $item->name = $request->name;
        $item->category_id = $request->category_id;
        $item->price = $request->price;
        $item->description = $request->desc;
        $item->save();
        return to_route('items.index');
    }
    public function edit($item_id)
    {
        return view(
            'dashboard.item.edit',
            [
                'data' => Item::find($item_id),
                'categories' => Category::get(),
            ]
        );
    }
    public function update(Request $request, $item_id)
    {
        $item = Item::find($item_id);
        $item->name = $request->name;
        $item->category_id = $request->category_id;
        $item->price = $request->price;
        $item->description = $request->desc;
        $item->save();
        return to_route('items.index');
    }
    public function destroy($item_id)
    {

        Item::where('id', $item_id)->delete();
        return to_route('items.index');
    }
}

resources/views/dashboard/item/create.blade.php
<!DOCTYPE html>
<html lang="ar">
@include('dashboard.layouts.header')


<body>
    @include('dashboard.layouts.nav-sidebar')

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Add new item</h1>
        </div>


        <section class="section">
            <div class="row">
                <div class="col-lg-12">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Add new item</h5>

                            <!-- General Form Elements -->
                            <form action="{{ route('items.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Name *</label>
                                        <input autocomplete="false" id="name" type="text" name="name"
                                            class="form-control" required>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Category *</label>
                                        <select required name="category_id" class="form-control">
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Price *</label>
                                        <input autocomplete="false" id="price" type="number" min="0" name="price"
                                            class="form-control" required>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Description</label>
                                        <textarea class="form-control" name="desc" id="desc"></textarea>
                                    </div>
                                </div>
                                <br>
                                <div class="row mb-3">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>

                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main>

    @include('dashboard.layouts.script')

</body>

</html>

resources/views/dashboard/item/edit.blade.php
<!DOCTYPE html>
<html lang="ar">
@include('dashboard.layouts.header')


<body>
    @include('dashboard.layouts.nav-sidebar')

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Add {{ $data->name }}</h1>
        </div>


        <section class="section">
            <div class="row">
                <div class="col-lg-12">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Add {{ $data->name }}</h5>

                            <!-- General Form Elements -->
                            <form action="{{ route('items.update',$data->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Name *</label>
                                        <input autocomplete="false" id="name" type="text" name="name"
                                            class="form-control" value="{{ $data->name }}" required>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Category *</label>
                                        <select name="category_id" class="form-control">
                                            <option selected value="{{ $data->category->id }}">{{ $data->category->name }}</option>

                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Price *</label>
                                        <input autocomplete="false" id="price" type="number" min="0"
                                            name="price" class="form-control" value="{{ $data->price }}" required>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="name" class="col-form-label">Description</label>
                                        <textarea class="form-control" name="desc" id="desc">{{ $data->description }}</textarea>
                                    </div>
                                </div>
                                <br>
                                <div class="row mb-3">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>

                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main>

    @include('dashboard.layouts.script')

</body>

</html>

resources/views/dashboard/item/index.blade.php
<!DOCTYPE html>
<html lang="ar">
@include('dashboard.layouts.header')


<body>
    @include('dashboard.layouts.nav-sidebar')

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Item List</h1>
        </div>


        <section class="section">
            <div class="row">
                <div class="col-lg-12">

                    <div class="card">
                        <div class="card-body">

                            <div class="col-12">
                                <div class="card recent-sales overflow-auto">

                                    <div class="card-body">
                                        <h5 class="card-title">Item <span>| List</span></h5>
                                        <table class="table table-borderless datatable">
                                            <thead>
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Category</th>
                                                    <th scope="col">Price</th>
                                                    <th scope="col">Price after discount</th>
                                                    <th scope="col">Description</th>
                                                    <th scope="col">Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($datas as $data)

                                                <tr>
                                                    <th scope="row"><a href="#">#{{ $data->id }}</a></th>
                                                    <td>{{ $data->name }}</td>
                                                    <td>
                                                        {{ $data->category->name }}
                                                        @if($data->category->depth >= 2)
                                                        ->
                                                        {{ $data->category->parent->name }}
                                                        @endif
                                                        @if($data->category->depth >= 3)
                                                        ->
                                                        {{ $data->category->parent->parent->name }}
                                                        @endif
                                                        @if($data->category->depth >= 4)
                                                        ->
                                                        {{ $data->category->parent->parent->parent->name }}
                                                        @endif
                                                    </td>
                                                    <td>{{ $data->price }}</td>
                                                    <td>{{ $data->price - $data->discount_price }}</td>
                                                    <td>{{ $data->description }}</td>
                                                    <td>
                                                        <a href="{{ route('items.edit', $data->id) }}"><span
                                                                class="badge bg-warning">Edit</span>
                                                        </a>
                                                        <a href="{{ route('items.destroy', $data->id) }}"><span
                                                                class="badge bg-danger">Delete</span>
                                                        </a>
                                                    </td>
                                                </tr>

                                                @endforeach

                                            </tbody>
                                        </table>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main>

    @include('dashboard.layouts.script')

</body>

</html>